/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;
import javax.swing.*;
import java.awt.*;
/**
 *
 * @author Pabos95
 */
public class VentanaEjecucion extends javax.swing.JFrame {

    /**
     * Creates new form VentanaEjecucion
     */
    public VentanaEjecucion() {
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TiempoEjecucion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        LongitudModAdministracionClientes = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        LongitudModAdministracionConsultas = new javax.swing.JTextField();
        NumConexionesDescartadas = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        LongitudModAdministracionTransacciones = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        LongitudModAdministracionProcesos = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        LongitudModAdministracionConsultas1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.lightGray);
        setPreferredSize(new java.awt.Dimension(640, 511));
        getContentPane().setLayout(null);

        jPanel1.setBackground(java.awt.Color.lightGray);
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tiempo de ejecucion:");
        this.add(jLabel1);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(32, 14, 370, 22);

        TiempoEjecucion.setEditable(false);
        jPanel1.add(TiempoEjecucion);
        TiempoEjecucion.setBounds(500, 20, 138, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Longitud cola modulo administracion clientes: ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 52, 420, 22);

        LongitudModAdministracionClientes.setEditable(false);
        jPanel1.add(LongitudModAdministracionClientes);
        LongitudModAdministracionClientes.setBounds(500, 50, 138, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Longitud cola modulo administracion consultas: ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 103, 410, 22);

        LongitudModAdministracionConsultas.setEditable(false);
        jPanel1.add(LongitudModAdministracionConsultas);
        LongitudModAdministracionConsultas.setBounds(500, 100, 138, 20);

        NumConexionesDescartadas.setEditable(false);
        jPanel1.add(NumConexionesDescartadas);
        NumConexionesDescartadas.setBounds(500, 260, 138, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Conexiones descartadas por el servidor");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 251, 380, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Longitud cola modulo administracion transacciones: ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 186, 460, 22);

        LongitudModAdministracionTransacciones.setEditable(false);
        jPanel1.add(LongitudModAdministracionTransacciones);
        LongitudModAdministracionTransacciones.setBounds(500, 180, 138, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Longitud cola modulo administracion procesos: ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 141, 400, 22);

        LongitudModAdministracionProcesos.setEditable(false);
        jPanel1.add(LongitudModAdministracionProcesos);
        LongitudModAdministracionProcesos.setBounds(500, 140, 138, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Longitud segunda cola modulo administracion consultas");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 209, 460, 33);

        LongitudModAdministracionConsultas1.setEditable(false);
        jPanel1.add(LongitudModAdministracionConsultas1);
        LongitudModAdministracionConsultas1.setBounds(500, 220, 138, 20);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/geometric-background.png")));
        jPanel1.add(jLabel9);
        jLabel9.setBounds(-33, -29, 900, 650);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 28, 640, 511);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TiempoEjecucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TiempoEjecucionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TiempoEjecucionActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
  public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEjecucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEjecucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEjecucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEjecucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaEjecucion().setVisible(true);
            }
        });
    }
   public void actualizarLongitudModAdministracionClientes(int nuevaLong){
       LongitudModAdministracionClientes.setText(String.valueOf(nuevaLong));
    }
 
   public void actualizarLongitudModAdministracionConsultas(int nuevaLong){       
     LongitudModAdministracionConsultas.setText(String.valueOf(nuevaLong));
   }
 public void actualizarLongitudModAdministracionProcesos(int nuevaLong){
       LongitudModAdministracionProcesos.setText(String.valueOf(nuevaLong));
   }
   public void actualizarLongitudModAdministracionTransacciones(int nuevaLong){
       LongitudModAdministracionTransacciones.setText(String.valueOf(nuevaLong));
    }
   public void actualizarTiempoActual(double nuevoTiempo){
       TiempoEjecucion.setText(String.valueOf(nuevoTiempo));
    }
   public void actualizarNumConexionesDescartadas(int nuevoNum){
       NumConexionesDescartadas.setText(String.valueOf(nuevoNum));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField LongitudModAdministracionClientes;
    private javax.swing.JTextField LongitudModAdministracionConsultas;
    private javax.swing.JTextField LongitudModAdministracionConsultas1;
    private javax.swing.JTextField LongitudModAdministracionProcesos;
    private javax.swing.JTextField LongitudModAdministracionTransacciones;
    private javax.swing.JTextField NumConexionesDescartadas;
    private javax.swing.JTextField TiempoEjecucion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
